// flow-typed signature: 07b4f8067539f5b070c02fb2b65ffbec
// flow-typed version: <<STUB>>/constant-case_v2.0.0/flow_v0.70.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'constant-case'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'constant-case' {
  declare module.exports: (value: string, locale?: string) => string;
}
